### PR TITLE
Add Ability to Perform DB Migrations & DB Mirroring

### PR DESCRIPTION
**Pull request by ashra-f**
We have added two key features to our database management capabilities: database migrations and database mirroring. We believe that these additions will significantly enhance the robustness, reliability, and agility of our database operations, enabling us to deliver a seamless and efficient experience to our users.

🪶 Database Migrations:

We have introduced a robust database migration system using Supabase, a powerful, open-source database tool. With this feature, developers can now create, manage, and push database migrations more easily and efficiently. We've integrated this with GitHub Actions, allowing for automatic and seamless handling of migrations. This automation reduces the chance of errors and helps maintain consistency across different environments.

🪞 Database Mirroring:

To further enhance the resilience of our database system, we have added database mirroring using the Snaplet tool. This feature provides a real-time, hot-standby replica of our primary database, ensuring that we can swiftly switch over with minimal downtime in the event of any disruptions. This addition will significantly increase our system's fault tolerance and availability.

### CODE REVIEW

**Comment by ashra-f** [comment]
The issue with the Deploy _Migrations to Production_ workflow is that the the required environment variables (SUPABASE_ACCESS_TOKEN & PRODUCTION_DB_PASSWORD) are not being assigned. I tried using CF but I kept getting this error:
Screenshot 2023-07-05 at 5 22 01 PM

Seems like CF is recommending I add Cloudflare credentials to [GitHub secrets](https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#add-cloudflare-credentials-to-github-secrets).

**Comment by ashra-f** [comment]
I'm connected to a demo db I created, not the actually the bundling-mvp db.

**Comment by ashra-f** [comment]
Supabase does not have migration rollback functionality. A workaround is creating a new migration that [undoes the previous migration's actions](https://supabase.com/docs/guides/cli/managing-environments#create-a-new-migration). However, I might look into Prisma later.

**Review by cheningD — APPROVED** [review]
LGTM! Merge

**Pull request merged**
